name: Run script.js manually

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies (if package.json exists)
        run: |
          if [ -f package.json ]; then
            npm install
          else
            echo "No package.json found, skipping npm install"
          fi

      - name: Run script.js
        run: node script.js

      - name: Debug - list files in 'dane' directory
        run: ls -la dane/

      - name: Commit and push the generated files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Debugging - sprawdź, jakie pliki zmieniły się po uruchomieniu script.js
          git status
          git diff

          # Wymuś dodanie wszystkich zmian
          git add -A

          # Sprawdź, czy są zmiany do commitowania
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Add generated chess stats"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
