name: Run script.js every 5 minutes

on:
  schedule:
    - cron: "*/1 * * * *"  # Uruchamia co 5 minut (UTC)
  workflow_dispatch:  # Możliwość ręcznego wywołania workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Run script.js
        run: node script.js

      - name: Commit and push the generated files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add dane/
          git commit -m "Add generated chess stats"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
