name: Run script.js daily

on:
  schedule:
    - cron: "25 23 * * *"  # Uruchamia codziennie o 23:25 UTC (00:25 CET)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"  # Możesz zmienić wersję

      - name: Run script.js
        run: node script.js  # Odpala Twój skrypt
